-- ====================================================================
-- SISTEMA EDUCATIVO "EDUCAR PARA TRANSFORMAR" - PARTE 3
-- Script de Persistencia Real, CRUD de Solicitudes y Roles en Supabase
-- Versión Endurecida y Defensiva contra Datos Legacy
-- ====================================================================

-- --------------------------------------------------------------------
-- BLOQUE 1: COMPLETAR TABLA public.inscripciones DE FORMA SEGURA
-- --------------------------------------------------------------------
-- Asegurar tabla base
CREATE TABLE IF NOT EXISTS public.inscripciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Agregar columnas faltantes sin fallar si ya existen
ALTER TABLE public.inscripciones 
    ADD COLUMN IF NOT EXISTS nombre TEXT,
    ADD COLUMN IF NOT EXISTS dni TEXT,
    ADD COLUMN IF NOT EXISTS nivel TEXT,
    ADD COLUMN IF NOT EXISTS email TEXT,
    ADD COLUMN IF NOT EXISTS mensaje TEXT,
    ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'pendiente';

-- Asegurar valor por defecto para 'estado' en registros preexistentes donde sea NULL
UPDATE public.inscripciones 
SET estado = 'pendiente' 
WHERE estado IS NULL;

-- Verificación no destructiva para aplicar NOT NULL solo si no hay filas legacy con NULL
DO $$
DECLARE
    v_filas_incompletas INT;
BEGIN
    -- Contar si existen registros legacy con columnas requeridas en NULL
    SELECT COUNT(*) INTO v_filas_incompletas
    FROM public.inscripciones
    WHERE nombre IS NULL OR dni IS NULL OR nivel IS NULL OR email IS NULL;

    IF v_filas_incompletas > 0 THEN
        RAISE NOTICE 'ADVERTENCIA: Se encontraron % registro(s) legacy con campos en NULL. NO se aplicaron restricciones NOT NULL en nombre/dni/nivel/email para evitar fallos destructivos. Revise la consulta de inspección al final del script para sanearlos.', v_filas_incompletas;
    ELSE
        -- Si la tabla está limpia o vacía, aplicar restricciones NOT NULL con total seguridad
        ALTER TABLE public.inscripciones
            ALTER COLUMN nombre SET NOT NULL,
            ALTER COLUMN dni SET NOT NULL,
            ALTER COLUMN nivel SET NOT NULL,
            ALTER COLUMN email SET NOT NULL;
        RAISE NOTICE 'Restricciones NOT NULL aplicadas correctamente en nombre, dni, nivel y email.';
    END IF;

    -- 'estado' siempre es seguro aplicarle NOT NULL gracias al valor por defecto
    ALTER TABLE public.inscripciones
        ALTER COLUMN estado SET NOT NULL;
END $$;

-- Constraint de validación para los estados permitidos con verificación de esquema y tabla
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
        WHERE nsp.nspname = 'public'
          AND rel.relname = 'inscripciones'
          AND con.conname = 'inscripciones_estado_check'
    ) THEN
        ALTER TABLE public.inscripciones
            ADD CONSTRAINT inscripciones_estado_check
            CHECK (estado IN ('pendiente', 'aprobada', 'rechazada'));
        RAISE NOTICE 'Constraint inscripciones_estado_check creado exitosamente en public.inscripciones.';
    ELSE
        RAISE NOTICE 'Constraint inscripciones_estado_check ya existe en public.inscripciones.';
    END IF;
END $$;


-- --------------------------------------------------------------------
-- BLOQUE 2: TABLA public.profiles Y SINCRONIZACIÓN DE USUARIOS
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    role TEXT NOT NULL DEFAULT 'estudiante',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT profiles_role_check CHECK (role IN ('admin', 'estudiante'))
);

-- Trigger SECURITY DEFINER con search_path seguro para auto-crear perfil en registro
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER 
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.profiles (id, email, role)
    VALUES (NEW.id, NEW.email, 'estudiante')
    ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Sincronizar usuarios preexistentes de auth.users hacia public.profiles
INSERT INTO public.profiles (id, email, role)
SELECT id, email, 'estudiante'
FROM auth.users
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email;


-- --------------------------------------------------------------------
-- BLOQUE 3: FUNCIÓN DE SEGURIDAD PARA VERIFICACIÓN DE ROL ADMIN
-- --------------------------------------------------------------------
-- Declara search_path seguro para evitar secuestro de funciones y recursión en RLS
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN 
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role = 'admin'
    );
END;
$$;


-- --------------------------------------------------------------------
-- BLOQUE 4: ACTIVACIÓN Y POLÍTICAS DE ROW LEVEL SECURITY (RLS)
-- --------------------------------------------------------------------

-- Activar RLS en ambas tablas
ALTER TABLE public.inscripciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Políticas para public.inscripciones:
-- 1. Inserción pública permitida para aspirantes desde el formulario de la landing
DROP POLICY IF EXISTS "inscripciones_insert_public" ON public.inscripciones;
CREATE POLICY "inscripciones_insert_public" ON public.inscripciones
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

-- 2. Lectura solo para administradores autenticados
DROP POLICY IF EXISTS "inscripciones_select_admin" ON public.inscripciones;
CREATE POLICY "inscripciones_select_admin" ON public.inscripciones
    FOR SELECT
    TO authenticated
    USING (public.is_admin());

-- 3. Actualización de estado solo para administradores autenticados
DROP POLICY IF EXISTS "inscripciones_update_admin" ON public.inscripciones;
CREATE POLICY "inscripciones_update_admin" ON public.inscripciones
    FOR UPDATE
    TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- 4. Eliminación solo para administradores autenticados
DROP POLICY IF EXISTS "inscripciones_delete_admin" ON public.inscripciones;
CREATE POLICY "inscripciones_delete_admin" ON public.inscripciones
    FOR DELETE
    TO authenticated
    USING (public.is_admin());


-- Políticas para public.profiles:
-- 1. Cada usuario autenticado puede leer su propio perfil (o admin puede leer cualquiera)
DROP POLICY IF EXISTS "profiles_select_own_or_admin" ON public.profiles;
CREATE POLICY "profiles_select_own_or_admin" ON public.profiles
    FOR SELECT
    TO authenticated
    USING (auth.uid() = id OR public.is_admin());

-- 2. Cada usuario puede actualizar su propio perfil pero NUNCA asignarse rol admin
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles
    FOR UPDATE
    TO authenticated
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id AND role = 'estudiante');

-- 3. Los administradores pueden gestionar perfiles de cualquier usuario (incluyendo roles)
DROP POLICY IF EXISTS "profiles_update_admin" ON public.profiles;
CREATE POLICY "profiles_update_admin" ON public.profiles
    FOR UPDATE
    TO authenticated
    USING (public.is_admin())
    WITH CHECK (public.is_admin());


-- --------------------------------------------------------------------
-- BLOQUE 5: ASIGNAR ROL DE ADMINISTRADOR (EJECUTAR CON EL EMAIL REAL)
-- --------------------------------------------------------------------
-- Para otorgar permisos de administrador a un usuario existente, ejecutar:
-- UPDATE public.profiles
-- SET role = 'admin'
-- WHERE email = 'CORREO_DEL_USUARIO_ADMIN@EJEMPLO.COM';


-- ====================================================================
-- BLOQUE 6: QUERIES DE VERIFICACIÓN POST-EJECUCIÓN
-- ====================================================================

-- A. Inspeccionar si existen registros legacy con columnas incompletas
SELECT id, created_at, nombre, dni, nivel, email, estado
FROM public.inscripciones
WHERE nombre IS NULL OR dni IS NULL OR nivel IS NULL OR email IS NULL;

-- B. Estructura y nulabilidad de public.inscripciones
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
AND table_name = 'inscripciones'
ORDER BY ordinal_position;

-- C. Listado de perfiles y roles registrados
SELECT id, email, role
FROM public.profiles;

-- D. Verificación de políticas RLS activas en inscripciones y profiles
SELECT policyname, cmd, roles
FROM pg_policies
WHERE schemaname = 'public'
AND tablename IN ('inscripciones', 'profiles')
ORDER BY tablename, policyname;
